### PR TITLE
Redirect support

### PR DESCRIPTION
**Pull request by MarchWorks**
There is some change that should be done like the support for when the routes end with `.html`

### CODE REVIEW

**Comment by MarchWorks** [comment]
Sorry for the repeated message I just deleted `package-lock` and updated the plugin `CHANGELOG` and `README`

**Comment by MarchWorks** [comment]
@egoist How do you plan to solve #57 ? By adding an option `netfly` to `saber-config.yml` `plugin options` which generate `page/index.html` for every `page.html`?

**Comment by egoist** [comment]
@MarchWorks I will create saber-plugin-netlify-redirect later

**Comment by MarchWorks** [comment]
@egoist should I give it a try I think it's quite easy because it's a stand alone. I will use this plugin index as a base and get the pages from `api.pages.values()` and there routes with `page.attributes.permalink`. This time it will be perfect

**Comment by egoist** [comment]
@MarchWorks 👌🏻I updated the docs. I also moved the api the saber-node.js because most likely we need to access `pages` to generate redirect routes.

**Comment by egoist** [comment]
For the Netlify plugin:

- if `.saber/public/_redirects` already exists, we should merge it with our redirect routes.
- Redirect all `/:page` to `:page.html` by default.

**Comment by egoist** [comment]
I'm merging this one, you can create another PR for the Netlify plugin.

**Pull request merged**
