### PR TITLE
fix(plugin-query-posts): convert backslash in pagination

### LINKED ISSUE #37: backslash in pagination
**./pages/index.md**:

```markdown
---
layout: index
permalink: /blog
---
```

maybe similar to #27

### PR DESCRIPTION
**Pull request by h404bi**
Close #37

### CODE REVIEW

**Comment by egoist** [comment]
I guess we can convert the backslash here once and for all: https://github.com/egoist/saber/blob/c4572b915ea172808fed30ba18b6ce3852237b10/packages/saber/lib/Pages.js#L17

**Comment by h404bi** [comment]
Not sure, but it sounds better.

**Comment by h404bi** [comment]
Need this fix to work, would you like to merge this before the better way coming out?

**Comment by h404bi** [comment]
closed by https://github.com/egoist/saber/commit/403fba15e9e2cd827c5650212be91e12fdb75f58

**Pull request closed without merging**
